export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Social } from "./Social";
export { default as Company } from "./Company";
export { default as Login } from "./Login";
export { default as Uniqlo } from "./Brand";
export { default as Header } from "./header";
export { default as BrandPage } from "./Brand"